name: movie
description: A new Flutter package project.

publish_to: 'none'

version: 0.0.1
homepage:

environment:
    sdk: '>=3.2.3 <4.0.0'
    flutter: '>=1.17.0'

dependencies:
    flutter:
        sdk: flutter
    core:
        path: ../core
    tv_series:
        path: ../tv_series
    search:
        path: ../search
    watchlist:
        path: ../watchlist
    dartz: ^0.10.0
    equatable: ^2.0.3
    flutter_bloc: ^8.1.1
    http: ^1.1.2
    rxdart: ^0.27.2
    flutter_dotenv: ^5.0.2
    flutter_rating_bar: ^4.0.1
    path_provider: ^2.0.11
    cached_network_image: ^3.3.1

dev_dependencies:
    bloc_test: ^9.1.0
    build_runner: ^2.2.0
    flutter_lints: ^3.0.1
    flutter_test:
        sdk: flutter
    mockito: ^5.0.16
    mocktail: ^1.0.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    # To add assets to your package, add an assets section, like this:
    # assets:
    # - .env
    #
    # For details regarding assets in packages, see
    # https://flutter.dev/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts in packages, see
    # https://flutter.dev/custom-fonts/#from-packages
